name: Restrict Push to outside-dev only

on:
  push:
    branches:
      - '*'  # すべてのブランチへの push イベントをトリガーする

jobs:
  restrict-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the push is to outside-dev branch
        run: |
          if [[ "$GITHUB_REF" != "refs/heads/outside-dev" ]]; then
            echo "You are not allowed to push to this branch.";
            exit 1;
          fi
